name: fragje
timezone: Europe/Oslo
markdown: kramdown
highlighter: pygments
source: ./jekyll
destination: ./public
layouts: ./jekyll/_layouts-automated
exclude: []
keep_files: ["assets", "styleguide"]
permalink: /:categories/:title/
